resources:
  - name: gke-cluster
    type: container.v1.cluster
    properties:
      zone: me-central1-a
      cluster:
        name: gke-cluster
        zone: me-central1-a
        nodeConfig:
          machineType: e2-standard-2
          diskSizeGb: 10
          oauthScopes:
            - "https://www.googleapis.com/auth/cloud-platform"
        initialNodeCount: 2
